DROP TABLE IF EXISTS url_checks;
DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
created_at TIMESTAMP NOT NULL
);

CREATE TABLE url_checks (
    id SERIAL PRIMARY KEY,
    status_code INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    h1 VARCHAR(255) NOT NULL,
    description text NOT NULL,
    url_id INT NOT NULL,
    FOREIGN KEY (url_id) REFERENCES urls(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);