dev:
	./gradlew run
clean:
	./gradlew clean
build:
	./gradlew clean build
install:
	./gradlew installDist
lint:
	./gradlew checkstyleMain
test:
	./gradlew test

report:
	./gradlew jacocoTestReport

.PHONY: build
