name: Java CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone App Repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle 8.7
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          build-root-directory: app
          
      - name: Build App
        working-directory: ${{github.workspace}}/app
        run: ./gradlew build jacocoTestReport

      - name: Create JacocoTestReport
        working-directory: ${{github.workspace}}/app
        run: ./gradlew jacocoTestReport
        
      - name: Publish Code Coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: ${{github.workspace}}/app/src/main/java
        with:
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
